export const AUDIT_ACTIONS = [
  "WORK_ENTRY_SUBMITTED",
  "WORK_ENTRY_RESUBMITTED",
  "DEPARTMENT_APPROVED",
  "DEPARTMENT_REJECTED",
  "PROJECT_APPROVED",
  "PROJECT_REJECTED",
  "DEPARTMENT_MANAGER_CHANGED",
  "PROJECT_MANAGER_CHANGED",
  "REPORT_CREATED",
  "REPORT_UPDATED",
  "REPORT_ACTIVATED",
  "REPORT_DEACTIVATED",
  "PROFILE_COMPLETED",

  "PERIOD_LOCKED",
  "PERIOD_UNLOCKED",
  "WORK_ENTRY_CREATED",
  "WORK_ENTRY_UPDATED",
  "WORK_ENTRY_DELETED",
  "USER_ROLE_CHANGED",
  "USER_DEPARTMENT_CHANGED",
  "USER_ACTIVATED",
  "USER_DEACTIVATED",
  "USER_UPDATED",
  "DEPARTMENT_CREATED",
  "DEPARTMENT_UPDATED",
  "DEPARTMENT_ACTIVATED",
  "DEPARTMENT_DEACTIVATED",
  "PROJECT_CREATED",
  "PROJECT_UPDATED",
  "PROJECT_ACTIVATED",
  "PROJECT_DEACTIVATED",
  "PROJECT_FILE_CREATED",
  "PROJECT_FILE_UPDATED",
  "PROJECT_FILE_ACTIVATED",
  "PROJECT_FILE_DEACTIVATED",
] as const;
export const AUDIT_ENTITIES = [
  "REPORT",
  "PERIOD",
  "WORK_ENTRY",
  "USER",
  "DEPARTMENT",
  "PROJECT",
  "PROJECT_FILE",
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];
export type AuditEntity = (typeof AUDIT_ENTITIES)[number];
export const auditEntityLabels: Record<AuditEntity, string> = {
  REPORT: "گزارش",
  PERIOD: "دوره",
  WORK_ENTRY: "فعالیت",
  USER: "کاربر",
  DEPARTMENT: "واحد",
  PROJECT: "پروژه",
  PROJECT_FILE: "گزارش",
};
export const auditActionLabels: Record<AuditAction, string> = {
  WORK_ENTRY_SUBMITTED: "ارسال گزارش",
  WORK_ENTRY_RESUBMITTED: "ارسال مجدد گزارش",
  DEPARTMENT_APPROVED: "تأیید مدیر واحد",
  DEPARTMENT_REJECTED: "رد مدیر واحد",
  PROJECT_APPROVED: "تأیید مدیر پروژه",
  PROJECT_REJECTED: "رد مدیر پروژه",
  DEPARTMENT_MANAGER_CHANGED: "تغییر مدیر واحد",
  PROJECT_MANAGER_CHANGED: "تغییر مدیر پروژه",
  REPORT_CREATED: "ایجاد گزارش",
  REPORT_UPDATED: "ویرایش گزارش",
  REPORT_ACTIVATED: "فعال‌سازی گزارش",
  REPORT_DEACTIVATED: "غیرفعال‌سازی گزارش",
  PROFILE_COMPLETED: "تکمیل مشخصات",

  PERIOD_LOCKED: "قفل دوره",
  PERIOD_UNLOCKED: "باز کردن دوره",
  WORK_ENTRY_CREATED: "ثبت فعالیت",
  WORK_ENTRY_UPDATED: "ویرایش فعالیت",
  WORK_ENTRY_DELETED: "حذف فعالیت",
  USER_ROLE_CHANGED: "تغییر نقش",
  USER_DEPARTMENT_CHANGED: "تغییر واحد کاربر",
  USER_ACTIVATED: "فعال‌سازی کاربر",
  USER_DEACTIVATED: "غیرفعال‌سازی کاربر",
  USER_UPDATED: "ویرایش مشخصات محلی کاربر",
  DEPARTMENT_CREATED: "ایجاد واحد",
  DEPARTMENT_UPDATED: "ویرایش واحد",
  DEPARTMENT_ACTIVATED: "فعال‌سازی واحد",
  DEPARTMENT_DEACTIVATED: "غیرفعال‌سازی واحد",
  PROJECT_CREATED: "ایجاد پروژه",
  PROJECT_UPDATED: "ویرایش پروژه",
  PROJECT_ACTIVATED: "فعال‌سازی پروژه",
  PROJECT_DEACTIVATED: "غیرفعال‌سازی پروژه",
  PROJECT_FILE_CREATED: "ایجاد گزارش",
  PROJECT_FILE_UPDATED: "ویرایش گزارش",
  PROJECT_FILE_ACTIVATED: "فعال‌سازی گزارش",
  PROJECT_FILE_DEACTIVATED: "غیرفعال‌سازی گزارش",
};
