export const AUDIT_ACTIONS = [
  "PERIOD_LOCKED",
  "PERIOD_UNLOCKED",
  "WORK_ENTRY_CREATED",
  "WORK_ENTRY_UPDATED",
  "WORK_ENTRY_DELETED",
  "USER_ROLE_CHANGED",
  "USER_DEPARTMENT_CHANGED",
  "USER_ACTIVATED",
  "USER_DEACTIVATED",
  "USER_UPDATED",
  "DEPARTMENT_CREATED",
  "DEPARTMENT_UPDATED",
  "DEPARTMENT_ACTIVATED",
  "DEPARTMENT_DEACTIVATED",
  "PROJECT_CREATED",
  "PROJECT_UPDATED",
  "PROJECT_ACTIVATED",
  "PROJECT_DEACTIVATED",
  "PROJECT_FILE_CREATED",
  "PROJECT_FILE_UPDATED",
  "PROJECT_FILE_ACTIVATED",
  "PROJECT_FILE_DEACTIVATED",
] as const;
export const AUDIT_ENTITIES = [
  "PERIOD",
  "WORK_ENTRY",
  "USER",
  "DEPARTMENT",
  "PROJECT",
  "PROJECT_FILE",
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];
export type AuditEntity = (typeof AUDIT_ENTITIES)[number];
export const auditEntityLabels: Record<AuditEntity, string> = {
  PERIOD: "دوره",
  WORK_ENTRY: "فعالیت",
  USER: "کاربر",
  DEPARTMENT: "واحد",
  PROJECT: "پروژه",
  PROJECT_FILE: "فایل پروژه",
};
export const auditActionLabels: Record<AuditAction, string> = {
  PERIOD_LOCKED: "قفل دوره",
  PERIOD_UNLOCKED: "باز کردن دوره",
  WORK_ENTRY_CREATED: "ثبت فعالیت",
  WORK_ENTRY_UPDATED: "ویرایش فعالیت",
  WORK_ENTRY_DELETED: "حذف فعالیت",
  USER_ROLE_CHANGED: "تغییر نقش",
  USER_DEPARTMENT_CHANGED: "تغییر واحد کاربر",
  USER_ACTIVATED: "فعال‌سازی کاربر",
  USER_DEACTIVATED: "غیرفعال‌سازی کاربر",
  USER_UPDATED: "ویرایش مشخصات محلی کاربر",
  DEPARTMENT_CREATED: "ایجاد واحد",
  DEPARTMENT_UPDATED: "ویرایش واحد",
  DEPARTMENT_ACTIVATED: "فعال‌سازی واحد",
  DEPARTMENT_DEACTIVATED: "غیرفعال‌سازی واحد",
  PROJECT_CREATED: "ایجاد پروژه",
  PROJECT_UPDATED: "ویرایش پروژه",
  PROJECT_ACTIVATED: "فعال‌سازی پروژه",
  PROJECT_DEACTIVATED: "غیرفعال‌سازی پروژه",
  PROJECT_FILE_CREATED: "ایجاد فایل پروژه",
  PROJECT_FILE_UPDATED: "ویرایش فایل پروژه",
  PROJECT_FILE_ACTIVATED: "فعال‌سازی فایل پروژه",
  PROJECT_FILE_DEACTIVATED: "غیرفعال‌سازی فایل پروژه",
};
